class Runable implements Runnable{
    public void run(){
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
        System.out.println("I am a thread not a threat");
    }
}
class Runable2 implements Runnable{
    public void run(){
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
        System.out.println("I am thread 2");
    }
}
public class Threading2 {
    public static void main(String[] args) {
        Runable bullet=new Runable();
        Runable2 bullet2=new Runable2();
        //we cannot execute run function by default
        Thread gun=new Thread(bullet);
        Thread gun2=new Thread(bullet2);
        gun.start();
        gun2.start();
    }
}
